<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="PropineTest" tests="4" failures="1" timestamp="27 May 2020 06:59:55 GMT" time="42.738" errors="0">
  <testcase name="valdiateLanguageSupportDateParser" time="1.225" classname="Suit1.DateValidationTestCase">
    <skipped/>
  </testcase> <!-- valdiateLanguageSupportDateParser -->
  <testcase name="valdiateLanguageSupportDateParser" time="0.949" classname="Suit1.DateValidationTestCase">
    <skipped/>
  </testcase> <!-- valdiateLanguageSupportDateParser -->
  <testcase name="valdiateLanguageSupportDateParser" time="0.959" classname="Suit1.DateValidationTestCase">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Wed May 27 09:00:00 UTC 2020] but found [Invalid date]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Wed May 27 09:00:00 UTC 2020] but found [Invalid date]
at Suit1.DateValidationTestCase.valdiateLanguageSupportDateParser(DateValidationTestCase.java:102)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- valdiateLanguageSupportDateParser -->
  <testcase name="validateDateParseFormat" time="0.953" classname="Suit1.DateValidationTestCase"/>
</testsuite> <!-- PropineTest -->
